# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Develop Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Develop Pipeline
      run: |
        echo "Deploying to dev environment"
        echo "sonar quality gate analysis"
        echo "release-1.0"
        echo "feature-1.0"
        echo "qa bug"
        echo "uat bug"
        echo "prod bug"
      shell: bash

