# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Feature Pipeline

on:
  create:
    branches: 
      - 'feature-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Feature Pipeline
      run: |
        echo "sonar quality gate analysis"
      shell: bash