# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: QA Pipeline

on:
  create:
    branches: 
      - staging
  push:
    branches:
      - staging


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: QA Pipeline
      run: echo "*****************************"
      run: echo "Deploying to qa environment"
      run: echo "sonar quality gate analysis"
      run: echo "release-1.0"
      run: echo "feature-1.0"
      run: echo "qa bug"
      run: echo "uat bug"
      run: echo "prod bug"
      run: echo "*****************************"
