# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: UAT Pipeline

on:
  create:
    branches: 
      - 'release-*'
  push:
    branches:
      - 'release-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: UAT Pipeline
      run: |
      echo "*****************************"
      echo "Deploying to uat environment"
      echo "sonar quality gate analysis"
      echo "release-1.0"
      echo "feature-1.0"
      echo "qa bug"
      echo "uat bug"
      echo "prod bug"
      echo "*****************************"
